### ISSUE TITLE
Can't install on 5.4.78-2-pve

### ISSUE THREAD

**Issue by abonforti** [stupidpupil/hp_n36-40-54l_health_led_drivers#5]
Hi, I am running proxmox kernel v. 5.4.78-2-pve on my N54L with BIOS revision:
```bash
root@hyper-v:~# cat /sys/class/dmi/id/bios_date
07/29/2011
root@hyper-v:~#
```

But I am encountering some troubles while installing:

```bash
hyper-v:~/devel/hp_n36-40-54l_health_led_drivers-master# dpkg -i dist/*.deb
(Reading database ... 106806 files and directories currently installed.)
Preparing to unpack .../gpio-sb8xx-dkms_20180507_all.deb ...

------------------------------
Deleting module version: 20180507
completely from the DKMS tree.
------------------------------
Done.
Unpacking gpio-sb8xx-dkms (20180507) over (20180507) ...
Preparing to unpack .../i2c-piix4-dkms_20180509_all.deb ...

------------------------------
Deleting module version: 20180509
completely from the DKMS tree.
------------------------------
Done.
Unpacking i2c-piix4-dkms (20180509) over (20180509) ...
Preparing to unpack .../softpwm-dkms_20180507_all.deb ...

------------------------------
Deleting module version: 20180507
completely from the DKMS tree.
------------------------------
Done.
Unpacking softpwm-dkms (20180507) over (20180507) ...
Setting up gpio-sb8xx-dkms (20180507) ...
Loading new gpio-sb8xx-20180507 DKMS files...
Building for 5.4.78-2-pve 5.4.106-1-pve
Building initial module for 5.4.78-2-pve
Done.

gpio-sb8xx.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.78-2-pve/updates/dkms/

depmod.......^[^[[C....

Backing up initrd.img-5.4.78-2-pve to /boot/initrd.img-5.4.78-2-pve.old-dkms
Making new initrd.img-5.4.78-2-pve
(If next boot fails, revert to initrd.img-5.4.78-2-pve.old-dkms image)
update-initramfs......

DKMS: install completed.
Module build for kernel 5.4.106-1-pve was skipped since the
kernel headers for this kernel does not seem to be installed.
Setting up i2c-piix4-dkms (20180509) ...
Loading new i2c-piix4-20180509 DKMS files...
Building for 5.4.78-2-pve 5.4.106-1-pve
Building initial module for 5.4.78-2-pve
Done.

Building for 5.4.78-2-pve 5.4.106-1-pve
Building initial module for 5.4.78-2-pve
Error! Bad return status for module build on kernel: 5.4.78-2-pve (x86_64)
Consult /var/lib/dkms/softpwm/20180507/build/make.log for more information.
dpkg: error processing package softpwm-dkms (--install):
 installed softpwm-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 softpwm-dkms
```
Logfile:
```c
hyper-v:~/devel/hp_n36-40-54l_health_led_drivers-master# cat /var/lib/dkms/softpwm/20180507/build/make.log
DKMS make.log for softpwm-20180507 for kernel 5.4.78-2-pve (x86_64)
Wed 31 Mar 2021 02:25:11 PM CEST
make: Entering directory '/var/lib/dkms/softpwm/20180507/build'
make -C /lib/modules/5.4.78-2-pve/build M=/var/lib/dkms/softpwm/20180507/build modules
make[1]: Entering directory '/var/lib/dkms/softpwm/20180507/build'
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
  CC [M]  /var/lib/dkms/softpwm/20180507/build/softpwm.o
/var/lib/dkms/softpwm/20180507/build/softpwm.c:214:3: error: 'struct class' has no member named 'class_attrs'; did you mean 'class_groups'?
  .class_attrs = soft_pwm_class_attrs,
   ^~~~~~~~~~~
   class_groups
/var/lib/dkms/softpwm/20180507/build/softpwm.c:214:17: error: initialization of 'const struct attribute_group **' from incompatible pointer type 'struct class_attribute *' [-Werror=incompatible-pointer-types]
  .class_attrs = soft_pwm_class_attrs,
                 ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/softpwm/20180507/build/softpwm.c:214:17: note: (near initialization for 'soft_pwm_class.class_groups')
/var/lib/dkms/softpwm/20180507/build/softpwm.c: In function 'soft_pwm_hrtimer_callback':
/var/lib/dkms/softpwm/20180507/build/softpwm.c:311:23: error: request for member 'tv64' in something not a structure or union
    if (desc->next_tick.tv64 <= now.tv64) {
                       ^
/var/lib/dkms/softpwm/20180507/build/softpwm.c:311:35: error: request for member 'tv64' in something not a structure or union
    if (desc->next_tick.tv64 <= now.tv64) {
                                   ^
/var/lib/dkms/softpwm/20180507/build/softpwm.c:321:21: error: request for member 'tv64' in something not a structure or union
  if (next_tick.tv64 > 0)
               ^
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:275: /var/lib/dkms/softpwm/20180507/build/softpwm.o] Error 1
make[1]: *** [Makefile:1757: /var/lib/dkms/softpwm/20180507/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.4.78-2-pve'
make: *** [Makefile:3: all] Error 2
make: Leaving directory '/var/lib/dkms/softpwm/20180507/build'
hyper-v:~/devel/hp_n36-40-54l_health_led_drivers-master#
```

Is there anything i can do to make it working?

**Comment by abonforti** [comment]
Sorry, noticed that has already been notified, hence, closing this
